### ISSUE TITLE
couldn't find "libsecrets.so"

### ISSUE THREAD

**Issue by alexbgameson** [klaxit/hidden-secrets-gradle-plugin#39]
`2021-05-05 11:34:20.567 10645-10968/com.nanonodes.servers E/AndroidRuntime: FATAL EXCEPTION: Thread-13
    Process: com.nanonodes.servers, PID: 10645
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nanonodes.servers-t6bctHCf0XzknxVEfyXDDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nanonodes.servers-t6bctHCf0XzknxVEfyXDDw==/lib/x86, /data/app/com.nanonodes.servers-t6bctHCf0XzknxVEfyXDDw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libsecrets.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.nanonodes.servers.Secrets.<clinit>(Secrets.kt:10)
        at com.nanonodes.servers.ui.login.PanelActivity$o.run(PanelActivity.java:1328)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by ben-j69** [comment]
Hello,

I would have appreciate a "Hello" and a bit of context before your error log.

It looks like you forgot to add externalNativeBuild, please follow the README or give more explanation.
