### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libsecrets.so" not found

### ISSUE THREAD

**Issue by Quentin22** [klaxit/hidden-secrets-gradle-plugin#62]
Hi,

By adding the plugin in my module (version 0.2.0), I was able to run this command `./gradlew hideSecret ...`.

I have enabled C++ files compilation in my module, then I was able to get my secret key from Kotlin code by calling `val key = Secrets().getYourSecretKeyName(packageName)`.

However, when I install the app and launch it, I have this exception :

`2022-07-04 16:41:41.790 19552-19552/com.vianavigo.androidlab.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vianavigo.androidlab.dev, PID: 19552
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsecrets.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.instantsystem.homearoundme.Secrets.<clinit>(Secrets.kt:10)
        at com.instantsystem.homearoundme.ui.home.HomeFragment.onViewCreated(HomeFragment.kt:338)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
`

I saw in an older issue that it could come from the NDK version. I have tested with some versions but nothing changed.
Did I miss something?
Do you have any idea about this issue please?

**Comment by Quentin22** [comment]
issue closed by following strictly these steps
- apply plugin
- hideSecret command
- activate ndk
Duplicate of https://github.com/klaxit/hidden-secrets-gradle-plugin/issues/24
