### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsecrets.so" not found

### ISSUE THREAD

**Issue by deepanshugupta1876** [klaxit/hidden-secrets-gradle-plugin#78]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsecrets.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)

**Comment by deepanshugupta1876** [comment]
After increasing the plugin version from 0.1.3 to 0.2.1, getting this crash in crashlytics for few users

**Comment by deepanshugupta1876** [comment]
Please do let me know, if you need any additional information from my end.

Please help me resolve this issue.

**Comment by ben-j69** [comment]
@deepanshugupta1876 upate version by version and check the CHANGELOG to understand why you have this error.

**Comment by ponvig** [comment]
I have the same problem..

**Comment by vitalyveldyasov** [comment]
I have the same issue

**Comment by vitalyveldyasov** [comment]
My solution:
1. Add into CMakeLists.txt:


```
cmake_minimum_required(VERSION 3.18.1)

add_library( # Specifies the name of the library.
        secrets

        # Sets the library as a shared library.
        SHARED

        # Provides a relative path to your source file(s).
        secrets.cpp )
```
version (in my case 3.18.1) can be depended on your project

2. run `./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] [-Ppackage=com.your.package]`
    this command generates 4 files: secrets.cpp, secrets.hpp, sha256.cpp, sha256.hpp and you need to set path to secrets.cpp in CMakeLists.txt. In my case both files are located in the same dir, so I put secrets.cpp
3. You should remove secrets.cpp, secrets.hpp, sha256.cpp, sha256.hpp , Secrets.kt every time before executing `./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] [-Ppackage=com.your.package]`. It is better to create separate gradle task for it.

**Comment by ben-j69** [comment]
Hello  @vitalyveldyasov thanks for the solution if it is working it is great.

How should I fix the library ? There is already a CMakeLists.

Thanks

**Comment by vitalyveldyasov** [comment]
What exactly should be fixed in library? Try to add into CMakesLists.txt a library name as I mentioned above, build the project and run gradle task like : ./gradlew hideSecretFromPropertiesFile -PpropertiesFileName=credentials.properties
where there are your keys in credentials.properties file

after that .so files should be generated and located in 
build/intermediates/merged_native_libs/experimentalRelease/out/lib/<platform_name>/libsecrets.so

**Comment by ben-j69** [comment]
@vitalyveldyasov there is already a CMakesList.txt https://github.com/klaxit/hidden-secrets-gradle-plugin/blob/master/src/main/resources/cpp/CMakeLists.txt

The problem might happen when the project already contain one.

**Comment by sherbaev** [comment]
I am also facing this issue 

`Fatal Exception: java.lang.UnsatisfiedLinkError`
`dlopen failed: couldn't map "/mnt/asec/com.sherbaev.me-1/base.apk!/lib/arm64-v8a/libsecrets.so" segment 0: Permission denied`

**Comment by patelayush** [comment]
I have been facing the same issue. This exception is coming up for a few of the devices in Crashlytics. Has anyone found any solution to the issue.? I am on the latest version of sdk v0.2.1.

**Comment by georgehany309** [comment]
i have the same issue with small portion of users, and i cannot figure out why it's working with some users and not working with others.
anyone have found a solution yet?

**Comment by boy12hoody** [comment]
if you guys use [R8 Obfuscation](https://developer.android.com/build/shrink-code) then you must include this rule in you proguard-rules.pro

`
-keepclasseswithmembers class * {
native <methods>;
}
`

This will instruct ProGuard to keep all native methods in any class it processes.

**Comment by radiKal07** [comment]
I have the same issue, a very very small percentage of users run into this issue.
Not sure how much Android version matter but the users with this problem have Android 10, Android 11 and Android 13.

**Comment by b-wissa** [comment]
> My solution:
> 
> 1. Add into CMakeLists.txt:
> 
> ```
> cmake_minimum_required(VERSION 3.18.1)
> 
> add_library( # Specifies the name of the library.
>         secrets
> 
>         # Sets the library as a shared library.
>         SHARED
> 
>         # Provides a relative path to your source file(s).
>         secrets.cpp )
> ```
> 
> version (in my case 3.18.1) can be depended on your project
> 
> 2. run `./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] [-Ppackage=com.your.package]`
>    this command generates 4 files: secrets.cpp, secrets.hpp, sha256.cpp, sha256.hpp and you need to set path to secrets.cpp in CMakeLists.txt. In my case both files are located in the same dir, so I put secrets.cpp
> 3. You should remove secrets.cpp, secrets.hpp, sha256.cpp, sha256.hpp , Secrets.kt every time before executing `./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] [-Ppackage=com.your.package]`. It is better to create separate gradle task for it.

This is what worked for me, thanks 🚀
